application:
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# cron
- url: /task/alert
  script: alert.app
  login: admin

- url: /task/report
  script: report.app
  login: admin

# task queue
- url: /task/messaging
  script: worker.app
  login: admin

# slash command
- url: /slash
  script: slash.app

# receive
- url: /receive
  script: receiver.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: pytz
  version: "latest"

skip_files:
- ^.*\.iml
- ^\.idea
- ^\.git
- ^(.*/)?.*\.pyc$
