application:
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /task/alert
  script: alert.app
  login: admin

- url: /slash
  script: slash.app

libraries:
- name: webapp2
  version: "2.5.2"
