application: zaim-alert-bot
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /task/alert
  script: alert.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.2"
